# Тема
 **Методы искусственного интеллекта. EDA. Линейная регрессия. Дерево решений. CatBoost. XGBoost. Нейронные сети (MLP)**

# Цель работы
Получение навыков анализа первичных данных и определение признаков взаимосвязи (EDA), понимания
моделей: линейная регрессия, дерево решений, CatBoost, XGBoost, нейронные
сети (MLP) и умения разрабатывать программу на языке Python для
реализации представленных моделей

## Задачи
1) Описать датасета и определить влияние признаков и выбрать признаки,
которые наиболее подходят для поставленной задачи предсказания (EDA).
2) Построить пайплйан (DVC) исходя из результатов EDA.
3) Реализовать линейную регрессию, определить весы, метрики и
ошибки.
4) Реализовать дерево решений, определить метрики и ошибки. Привести
рисунок первых узлов дерева решений.
5) Реализовать CatBoost, определить метрики и ошибки. Выгрузить
Feature Importance.
6) Реализовать XGBoost, определить метрики и ошибки. Выгрузить
Feature Importance.
7) Реализовать нейронную сети, определить метрики, ошибки, кривые
обучения, гимтограммы весов с интерпретацией и график из Tensorboard.
8) Выгрузить конечный вычислительный граф DVC.
9) Построить сводную таблицу с метриками и сделать вывод какая модель
отработала лучше и почему.
10) Сделать вывод по работе.

# Ход работы

# **I - EDA - Explanatory Data Analysis (Разведочный анализ данных)**

# **1. Импортирование библиотек**

In [1]:
import pandas as pd
import os
import random
import re
import sys
import csv
import json
import yaml
import numpy as np

# **Конфигурация**

In [2]:
with open('D://HereAgain//CALOIRO 2025//Programming//LAB_MAI_01//Config//paramts.yaml', 'r') as config_file:
    config = yaml.safe_load(config_file)

os.chdir(config['base']['root_project_dir'])

print(config)

{'base': {'random_state': 42, 'test_size': 0.2, 'root_project_dir': 'D:\\HereAgain\\CALOIRO 2025\\Programming\\LAB_MAI_01'}, 'data': {'raw_dataset_csv': 'Data/Raw/test_scores.csv', 'features_path': 'Data/Features/features.csv', 'processed_dataset_csv': 'Data/Processed/test_scores_processed.csv', 'dataset_x_path_np': 'Data/Processed/data_x.npy', 'dataset_y_path_np': 'Data/Processed/data_y.npy', 'train_path': 'Data/Processed/train.csv', 'test_path': 'Data/Processed/test.csv', 'target_column': 'posttest'}, 'reports': {'ydata_report_path': 'Reports/ydata_report1.html', 'dvclive_path': 'dvclive/', 'metrics_path': 'Reports/metrics/', 'figures_path': 'Reports/figures/'}, 'models': {'models_path': 'models/', 'linear': {'n_jobs': None}, 'decision_tree': {'criterion': 'squared_error', 'max_depth': 10, 'min_samples_split': 2, 'min_samples_leaf': 3, 'random_state': 42}, 'xgboost': {'n_estimators': 200, 'learning_rate': 0.05, 'max_depth': 10, 'subsample': 0.8, 'colsample_bytree': 0.75, 'random_state': 42}, 'catboost': {'iterations': 300, 'depth': 4, 'learning_rate': 0.05, 'loss_function': 'RMSE', 'verbose': False, 'random_seed': 42}, 'ann': {'dataset_params': {'validation_split': 0.2, 'batch_size': 16, 'random_state': 42}, 'model_params': {'n_hidden_layers': 4, 'n_neurons': 32, 'activation': 'tanh', 'learning_rate': 0.001}, 'train_params': {'epochs': 100, 'verbose': 0}}}}

# **2. Загрузка данных**

In [3]:
df = pd.read_csv(config['data']['raw_dataset_csv'])
df

,school,school_setting,school_type,classroom,teaching_method,n_student,student_id,gender,lunch,pretest,posttest
0,ANKYI,Urban,Non-public,6OL,Standard,20.0,2FHT3,Female,Does not qualify,62.0,72.0
1,ANKYI,Urban,Non-public,6OL,Standard,20.0,3JIVH,Female,Does not qualify,66.0,79.0
2,ANKYI,Urban,Non-public,6OL,Standard,20.0,3XOWE,Male,Does not qualify,64.0,76.0
3,ANKYI,Urban,Non-public,6OL,Standard,20.0,556O0,Female,Does not qualify,61.0,77.0
4,ANKYI,Urban,Non-public,6OL,Standard,20.0,74LOE,Male,Does not qualify,64.0,76.0
...,...,...,...,...,...,...,...,...,...,...,...
1979,ZOWMK,Urban,Public,ZBH,Standard,30.0,S4I5S,Male,Qualifies for reduced/free lunch,39.0,50.0
1980,ZOWMK,Urban,Public,ZBH,Standard,30.0,T8LSK,Female,Does not qualify,39.0,55.0
1981,ZOWMK,Urban,Public,ZBH,Standard,30.0,VNP26,Female,Qualifies for reduced/free lunch,38.0,46.0
1982,ZOWMK,Urban,Public,ZBH,Standard,30.0,YUEIH,Male,Qualifies for reduced/free lunch,46.0,53.0
1983,ZOWMK,Urban,Public,ZBH,Standard,30.0,ZVCQ8,Male,Qualifies for reduced/free lunch,41.0,48.0

In [4]:
df.describe()

         n_student      pretest    posttest
count  1984.000000  1984.000000  1984.00000
mean     22.769153    54.980847    67.12500
std       4.248477    13.558027    13.93532
min      14.000000    22.000000    32.00000
25%      20.000000    44.000000    56.00000
50%      22.000000    56.000000    68.00000
75%      27.000000    65.000000    77.00000
max      31.000000    93.000000   100.00000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1984 entries, 0 to 1983
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   school           1984 non-null   object
 1   school_setting   1984 non-null   object
 2   school_type      1984 non-null   object
 3   classroom        1984 non-null   object
 4   teaching_method  1984 non-null   object
 5   n_student        1984 non-null   float64
 6   student_id       1984 non-null   object
 7   gender           1984 non-null   object
 8   lunch            1984 non-null   object
 9   pretest          1984 non-null   float64
 10  posttest         1984 non-null   float64
dtypes: float64(3), object(8)
memory usage: 170.6+ KB

In [6]:
df.var(numeric_only=True)

n_student     18.049557
pretest      183.820107
posttest     194.193142
dtype: float64

Проверка наличия пустых строк

In [7]:
df.isnull().sum()

school             0
school_setting     0
school_type        0
classroom          0
teaching_method    0
n_student          0
student_id         0
gender             0
lunch              0
pretest            0
posttest           0
dtype: int64

В данных отсутствуют пустые строки

# **3. Подготовка признаков**
## 3.1. Удаление не полезных признаков

1) Характеристика "student_id" содержит множество уникальных категорий, и они просто являются идентификаторами, не несут важный смыл для обучения.

2) У характеристик "school" и "classroom" также имеют слишком много категорий, что преоброзует много колонок при кодировании с помощью "OneHotEncoder", и также имеет риск переобучения.

3) Поэтому мы будем пренебрегать этими характеристиками/признаками: student_id, school и classroom.

In [8]:
df.drop(['student_id', 'school', 'classroom'], axis=1, inplace=True)
df

,school_setting,school_type,teaching_method,n_student,gender,lunch,pretest,posttest
0,Urban,Non-public,Standard,20.0,Female,Does not qualify,62.0,72.0
1,Urban,Non-public,Standard,20.0,Female,Does not qualify,66.0,79.0
2,Urban,Non-public,Standard,20.0,Male,Does not qualify,64.0,76.0
3,Urban,Non-public,Standard,20.0,Female,Does not qualify,61.0,77.0
4,Urban,Non-public,Standard,20.0,Male,Does not qualify,64.0,76.0
...,...,...,...,...,...,...,...,...
1979,Urban,Public,Standard,30.0,Male,Qualifies for reduced/free lunch,39.0,50.0
1980,Urban,Public,Standard,30.0,Female,Does not qualify,39.0,55.0
1981,Urban,Public,Standard,30.0,Female,Qualifies for reduced/free lunch,38.0,46.0
1982,Urban,Public,Standard,30.0,Male,Qualifies for reduced/free lunch,46.0,53.0
1983,Urban,Public,Standard,30.0,Male,Qualifies for reduced/free lunch,41.0,48.0

# 3.2.  Подготовка категориальных признаков

In [9]:
from sklearn.preprocessing import OneHotEncoder, LabelBinarizer

for col in ['gender', 'lunch', 'school_type', 'teaching_method']:
    lb = LabelBinarizer()
    df[col] = lb.fit_transform(df[col])

for col in ['school_setting']:
    ohe = OneHotEncoder()
    encoded = ohe.fit_transform(df[[col]]).toarray()
    df = df.join(pd.DataFrame(encoded, columns=[f"{col}_{c}" for c in ohe.categories_[0]], index=df.index))
    df.drop(col, axis=1, inplace=True)   
df

,school_type,teaching_method,n_student,gender,lunch,pretest,posttest,school_setting_Rural,school_setting_Suburban,school_setting_Urban
0,0,1,20.0,0,0,62.0,72.0,0.0,0.0,1.0
1,0,1,20.0,0,0,66.0,79.0,0.0,0.0,1.0
2,0,1,20.0,1,0,64.0,76.0,0.0,0.0,1.0
3,0,1,20.0,0,0,61.0,77.0,0.0,0.0,1.0
4,0,1,20.0,1,0,64.0,76.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1979,1,1,30.0,1,1,39.0,50.0,0.0,0.0,1.0
1980,1,1,30.0,0,0,39.0,55.0,0.0,0.0,1.0
1981,1,1,30.0,0,1,38.0,46.0,0.0,0.0,1.0
1982,1,1,30.0,1,1,46.0,53.0,0.0,0.0,1.0
1983,1,1,30.0,1,1,41.0,48.0,0.0,0.0,1.0

## Пояснения
Для кодирования признаков, содержащих только две категории или значения (бинарные признаки, например, пол) используется "LabelBinarizer". А для кодирования признаков, содержащих больше, чем две категории применяется "OneHotEncoder".
1) gender:
    1 - male
    0 - female

2) lunch:
    1 - Qualifies to reduced/free lunch
    0 - Does not qualify

3) school type:
    1 - Public
    0 - Non-public

4) teaching method:
    1 - Standard
    0 - Experimental

3.3. Подготовка числовых признаков

1) Для числовых признаков (n_student и pretest) выполняем НОРМАЛИЗАЦИЮ, так как у них высокие дисперсии.
2) protest - это целевая функция (target),то есть, что хотим предсказать, поэтому не трогаем.

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df[['n_student','pretest']] = scaler.fit_transform(df[['n_student','pretest']])
df

,school_type,teaching_method,n_student,gender,lunch,pretest,posttest,school_setting_Rural,school_setting_Suburban,school_setting_Urban
0,0,1,-0.651963,0,0,0.517843,72.0,0.0,0.0,1.0
1,0,1,-0.651963,0,0,0.812945,79.0,0.0,0.0,1.0
2,0,1,-0.651963,1,0,0.665394,76.0,0.0,0.0,1.0
3,0,1,-0.651963,0,0,0.444067,77.0,0.0,0.0,1.0
4,0,1,-0.651963,1,0,0.665394,76.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1979,1,1,1.702415,1,1,-1.178997,50.0,0.0,0.0,1.0
1980,1,1,1.702415,0,0,-1.178997,55.0,0.0,0.0,1.0
1981,1,1,1.702415,0,1,-1.252773,46.0,0.0,0.0,1.0
1982,1,1,1.702415,1,1,-0.662568,53.0,0.0,0.0,1.0
1983,1,1,1.702415,1,1,-1.031446,48.0,0.0,0.0,1.0

# **4. Генерация отчёта**

In [11]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df, title="Data Profiling Report", explorative=True)
profile.to_file(config['reports']['ydata_report_path'])

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 10/10 [00:00<00:00, 33.63it/s]
c:\Users\User\anaconda3\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 9 9 9]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
c:\Users\User\anaconda3\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[9 9 9 ... 9 9 9]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
c:\Users\User\anaconda3\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 9 ... 0 9 9]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(
c:\Users\User\anaconda3\Lib\site-packages\ydata_profiling\model\pandas\discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 9 9 9]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# **5. Сохранение полученных  данных**

In [12]:
# save data
df.to_csv(config['data']['features_path'], index=False)

data_x, data_y = np.array(df.drop('posttest', axis=1)), np.array(df['posttest'])
np.save(config['data']['dataset_x_path_np'], data_x)
np.save(config['data']['dataset_y_path_np'], data_y)

# **6. Выход по этапу EDA**

## 1. Предпосылки для для преобразований

- Было проверено отсутствие пустых строк, поэтому никаких дополнительных процедур не потребовалось.

- Была рассчитана дисперсия числовых характеристик, и для характеристик с высокой дисперсией было решено применить нормализацию, которая заключается в преобразовании значений в один масштаб, что ускоряет и улучшает процесс обучения данных.

- Для категориальных характеристик были сгенерированы числовые интерпретации с использованием метода «One Hot», который создает новые столбцы, чтобы они также учитывались при обучении.

## 2. Были проведены преобразования для подготовки признаков:

а) Категориальные признаки:
- gender, lunch, school_type, teaching_method → бинарное кодирование (LabelBinarizer)
- school_setting → one-hot кодирование (3 субкатегории, то есть, 3 новые колонки)

b) Числовые признаки:
    - n_student и pretest → нормализация (StandardScaler)

с) Стоит отметить, что признаки "student_id", "school" и "classroom" были удалены из-за их высок дисперсия и мало значимости для обучения, с риском переобучения.

## 3. Результаты преобразований
- Было получено 10 столбцов: 3 новых столбца и 3 проигнорированных (student_id, school, classroom);

- Было получено 4 бинарные характеристики: gender, lunch, school_type, teaching_method;

- Была получена 1 характеристика one-hot: school_setting.

# **II - Обучение данных**

## **Разделение данных**
 - test - тестовая
 - train - обучающая

In [13]:
with open("Config/paramts.yaml", "r") as f:
    config = yaml.safe_load(f)

x_path = config['data']['dataset_x_path_np']
y_path = config['data']['dataset_y_path_np']

X = np.load(x_path)
y = np.load(y_path)

print(X.shape)
print(y.shape)

(1984, 9)
(1984,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=config['base']['test_size'],
    random_state=config['base']['random_state']
)

print("Train:", X_train.shape, y_train.shape)
print("Test:", X_test.shape, y_test.shape)

Train: (1587, 9) (1587,)
Test: (397, 9) (397,)

# **1. Реализация линейной регрессии**

**Линейная регрессия** - это метод анализа данных и алгоритм машинного обучения, который моделирует зависимость между одной или несколькими независимыми переменными (факторами) и зависимой переменной (целевым значением) в виде прямой линии.

![Alt text](../Reports/figures/linear_coefficients.png)

# **2. Реализация дерева решений**

![Alt text](../Reports/figures/decision_tree_structure.png)

# **3. Реализация CatBoost**

![Alt text](../Reports/figures/catboost_feature_importance.png)

# **4. Реализация XGBoost**

![Alt text](../Reports/figures/xgboost_feature_importance.png)

# **5. Реализация нейронной сети (Artificial Neural Network)**

![Alt text](../Reports/figures/ann_weights_layer_1.png)

![Alt text](../Reports/figures/ann_weights_layer_2.png)

![Alt text](../Reports/figures/ann_weights_layer_3.png)

![Alt text](../Reports/figures/ann_weights_layer_4.png)

![Alt text](../Reports/figures/ann_weights_layer_5.png)

Кривые обучения

![Alt text](../Reports/figures/ann_loss_curve.png)

# **6. Сравнительная таблица метрик качества моделей**

1) **RMSE (Root Mean Squared Error/ среднеквадратичная ошибка)** - это метрика, показывающая, насколько сильно в среднем предсказанные моделью значения отличаются от реальных (фактических) данных => **Минимальная** 

2) **MAE (Mean Absolute Error/ средняя абсолютная ошибка)** - это метрика, которая показывает средний модуль отклонения предсказанных значений от фактических в задачах регрессии, не смотря в какую сторону (в плюс или минус) была сделана ошибка => **Минимальная** 

3) **R2 (Коэффициент детерминации)** показывает, насколько хорошо построенная регрессионная модель описывает реальные данные, измеряя долю дисперсии зависимой переменной, объясненную независимыми переменными => **Максимальная**

In [24]:
# Cравнение метрик

results = []

base_path = "dvclive"

for model_name in os.listdir(base_path):
    model_path = os.path.join(base_path, model_name)
    
    if os.path.isdir(model_path):
        metrics_file = os.path.join(model_path, "metrics.json")
        
        if os.path.exists(metrics_file):
            with open(metrics_file, "r") as f:
                data = json.load(f)
            
            test_metrics = data.get("test", {})
            
            results.append({
                "Model": model_name,
                "RMSE": test_metrics.get("rmse"),
                "MAE": test_metrics.get("mae"),
                "R2": test_metrics.get("r2")
            })
            
df_results = pd.DataFrame(results)
styled_df = df_results = df_results.style.format({
    "RMSE": "{:.7f}",
    "MAE": "{:.7f}",
    "R2": "{:.7f}"
}).background_gradient(cmap="plasma")

styled_df
#df_results

# **Выводы**

1) Такие метрики как ошибку,  и така как,  зависимость между данными нелинейная, линейная регрессия обладает высокиими значениями (худжими). То есть, нелинейные модели точнее.

2) Из полученных результатов CatBoost - самая лучшая модель, так как обладал наименьшей ошибкой,  то есть, модель лучше всего уловила зависимость в данных.

LAB_MAI_01/
├── Data/
│   ├── Raw/
│   ├── Processed/
├── Src/
│   ├── Data/
│   │   ├── Make_dataset.py
│   ├── Models
│   │   ├── train_ann.py
│   │   ├── train_CatBoost.py
│   │   ├── train_decision_tree.py
│   │   ├── train_linear.py
│   │   ├── train_XGboost.py
│   │   ├── train_utils.py
│   ├── Test/
│   │   ├── test_ann.py
│   │   ├── test_CatBoost.py
│   │   ├── test_descision_tree.py
│   │   ├── test_linear.py
│   │   ├── test_utils.py
│   │   ├── test_XGboost

Конечный вычислительный граф DVC

![Alt text](dvc_pipeline.png)